services:
  controller:
    build:
      context: .
      dockerfile: slurm-controller.Dockerfile
    container_name: sspa_slurm_controller
    cpus: 4
    mem_limit: 4g
    hostname: controller
    networks:
      - sspa_net
    environment:
      - SLURM_NODE_LIST=worker1,worker2
    volumes:
      - slurm-state:/var/spool/slurm
      - munge-key:/etc/munge
      - slurm-config:/slurm-config
      - ./work:/work
      - ./scratch:/scratch
      - ./sspa-home:/home/sspa
    ports:
      - "6817:6817"
      - "6818:6818"
      - "2222:22"

  worker1:
    build:
      context: .
      dockerfile: slurm-worker.Dockerfile
    container_name: sspa_slurm_worker1
    cpus: 4
    mem_limit: 4g
    hostname: worker1
    networks:
      - sspa_net
    environment:
      - SLURM_NODE_CPUS=4
      - SLURM_NODE_REAL_MEMORY_MB=4096
      - SLURM_NODE_SOCKETS=1
      - SLURM_NODE_THREADS_PER_CORE=1
    volumes:
      - munge-key:/etc/munge
      - slurm-config:/slurm-config
      - ./work:/work
      - ./scratch:/scratch
      - ./sspa-home:/home/sspa

  worker2:
    build:
      context: .
      dockerfile: slurm-worker.Dockerfile
    container_name: sspa_slurm_worker2
    cpus: 4
    mem_limit: 4g
    hostname: worker2
    networks:
      - sspa_net
    environment:
      - SLURM_NODE_CPUS=4
      - SLURM_NODE_REAL_MEMORY_MB=4096
      - SLURM_NODE_SOCKETS=1
      - SLURM_NODE_THREADS_PER_CORE=1
    volumes:
      - munge-key:/etc/munge
      - slurm-config:/slurm-config
      - ./work:/work
      - ./scratch:/scratch
      - ./sspa-home:/home/sspa

  # jupyter:
  #   build:
  #     context: .
  #     dockerfile: jupyter.Dockerfile
  #   container_name: sspa_jupyter
  #   networks:
  #     - sspa_net
  #   ports:
  #     - "8888:8888"
  #   command:
  #     - jupyter
  #     - lab
  #     - --ip=0.0.0.0
  #     - --no-browser
  #     - --port=8888
  #     - --NotebookApp.token=
  #     - --NotebookApp.password=
  #     - --allow-root

networks:
  sspa_net:
    driver: bridge
volumes:
  slurm-state:
  munge-key:
  slurm-config:
